### PR TITLE
Screenshots script docs

### PR DESCRIPTION
**Pull request by DHRUVJ2003**
I have added some screenshots in the docs for the interfaces of the pop up menus of the scripts.
Do tell me if any other changes need to be made.
Thank you

### CODE REVIEW

**Comment by ghutchis** [comment]
Can you please add the image assets to the pull request and use relative paths?

**Comment by DHRUVJ2003** [comment]
I had tried to do that but only the link to that image was being displayed in the readme file. 
the image was being displayed like this 
image

**Comment by ghutchis** [comment]
You need to make sure that you `git add` the appropriate image files.

**Comment by DHRUVJ2003** [comment]
I have tried it many times but the images aren't been displayed

**Comment by DHRUVJ2003** [comment]
Even the other images are not being displayed for example images [here ](https://github.com/DHRUVJ2003/two.avogadro.cc/blob/screenshots_script_docs/source/develop/scripts/install.md)

**Comment by DHRUVJ2003** [comment]
Is there any other way to solve this

**Comment by DHRUVJ2003** [comment]
Are you able to see the screenshots folder? I am able to see that the images have been pushed but github is not displaying the images

**Comment by DHRUVJ2003** [comment]
Hello sir @ghutchis. 
Can you please confirm whether now the screenshots are visible. I think I was not able to see those images probably due to some net issue I think. but now from my side I am able to see them.
If you are also able to view them, Kindly let me know if there are other changes that need to be done or merge the pr if everything is apt 
thank you!

**Comment by ghutchis** [comment]
Yes, I can see the images, thanks.

The images should go into `_static` and then you can refer to them like:
```
<img src="../../_static/Caffeine.png"
```

(The path may have different numbers of ../ to get to the right directory.)

**Comment by DHRUVJ2003** [comment]
Okay, thanks ....I have made the necessary changes and extremely sorry for unnecessary delay and inconvenience caused due the images not being visible.
I think we are now good to go.

**Comment by ghutchis** [comment]
Great, thanks.

**Pull request merged**
