### PR TITLE
Add font

### PR DESCRIPTION
**Pull request by rivercory**
@ghutchis Added Poppins font for better readability!

### CODE REVIEW

**Comment by rivercory** [comment]
화면 캡처 2024-09-03 224402

Isn't it cool?

**Comment by ghutchis** [comment]
As I said, please post at https://discuss.avogadro.cc (with screenshot) to make your argument for the rest of the community.

**Comment by rivercory** [comment]
https://discuss.avogadro.cc/t/change-font-to-poppins/5563

**Comment by rivercory** [comment]
@ghutchis Let's discuss this topic again after the project has developed further!

**Comment by ghutchis** [comment]
@rivercory - perfect. We'd definitely welcome font / style tweaks as the docs get closer to finish. Thanks!

**Pull request closed without merging**
