### PR TITLE
Move to modern project management with pyproject.toml

### PR DESCRIPTION
**Pull request by matterhorn103**

### CODE REVIEW

**Review by ghutchis — APPROVED** [review]

**Comment by ghutchis** [comment]
Can you please also update the deploy script:
https://github.com/Avogadro/two.avogadro.cc/blob/f3df0ccb650f9d32958fe1cf86bc3b07e03f91b1/.github/workflows/build.yml#L43

**Comment by matterhorn103** [comment]
Sure. Also with versions or just to make sure the package lists are in sync?

**Comment by matterhorn103** [comment]
[e83fc07](https://github.com/Avogadro/two.avogadro.cc/pull/93/commits/e83fc072167038c54cb04f153e10bfb5bd6464ac) would switch the project to using [uv](https://github.com/astral-sh/uv) for project and environment management.

Using uv means the dependencies will always stay in sync, and the environment used by GitHub Actions to build the docs can be identical to that used by us to write them. It's also significantly faster than pip at doing the dependency resolution, though I imagine the time spent on that step is small in comparison to the doxygen analysis. 

Moving to uv is a distinct step from just moving to `pyproject.toml`, so am happy for the last commit to be reverted/taken out of this PR and put into a different one for further discussion.

**Comment by ghutchis** [comment]
Yeah, let's move the `uv` commit to a different PR. I think it's fine, but it's at least worth some discussion.

My main thought was "oh, I just noticed the action doesn't even use the `requirements.txt` much less the `pyproject.toml`" 🚀

**Comment by matterhorn103** [comment]
> My main thought was "oh, I just noticed the action doesn't even use the requirements.txt much less the pyproject.toml" 🚀

Yep, sadly the pip team, or at least one of its members, has been very resistant to adding support for simply installing the set of dependencies.
I'll change this PR so that uv is still used but only to install the deps from `pyproject.toml` via the `uv pip` interface. That way we'll still benefit from not having to manually maintain the list in the actions yaml file, but the wider-reaching changes can be discussed further in a separate PR.

**Pull request merged**
